version: '3.2'

services:
  mysql_db:
    image: mysql:8
    restart: always
#    ports:
#      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 523524
    volumes:
      - ./dbdata:/var/lib/mysql/
  python:
    image: test
    restart: always
    ports:
      - "5000:5000"

